vtex-apps/b2b-organizations

CHANGELOG.md, react/components/EditUserModal.tsx, react/components/NewUserModal.tsx, react/components/OrganizationDetails.tsx, react/components/OrganizationUsersTable.tsx
QA reported that when using the My Account > My Organization UI, if you add a new cost center and then immediately either attempt to add a user or edit an existing user, the newly created cost center was not shown in the dropdown and the user could not be assigned to it. 
This PR fixes the issue by disabling the GraphQL cache for the relevant queries and refetching the data after the cost center is created.
New version linked in https://b2bsuite--sandboxusdev.myvtex.com
Log in as an Organization Admin, go to My Account > My Organization, add a new cost center, then (without refreshing the page) try to add or edit a user. The new cost center should appear as an option in the dropdown within the modal.
=> [B2BORGS-69] Update cost centers dropdown after adding new cc

CHANGELOG.md, react/admin/OrganizationDetails.tsx
In the organizations admin panel, if a price table, payment term, or product collection is assigned to an organization, this PR updates the "Available" table to grey out the assigned option. To make it even more obvious that it has been assigned, a checkmark icon is also added next to the assigned option.
Linked here: https://b2bsuite--sandboxusdev.myvtex.com/admin/b2b-organizations/organizations/1574d7ea-1250-11ec-82ac-020154316047/
=> [B2BORG-77] Visual indicator for assigned selections

CHANGELOG.md, react/components/OrganizationUsersTable.tsx
When attempting to impersonate a user, frontend will no longer block impersonation if the user's `userId` is null. The impersonation mutation from `vtex.b2b-organizations-graphql` will attempt to determine the `userId` from the user's `clId`. If it can't, an error will be returned which will trigger the frontend to display an appropriate message.
Related to this PR: https://github.com/vtex-apps/b2b-organizations-graphql/pull/20
Linked here: https://b2bsuite--sandboxusdev.myvtex.com
=> [B2BORG-85] Improve impersonation UI

CHANGELOG.md, react/admin/OrganizationDetails.tsx, react/components/OrganizationDetails.tsx, react/components/OrganizationUsersTable.tsx
Our QA team reported a few UI bugs where changes to a cost center (i.e. deleting a cost center, or adding/removing addresses) would not be reflected in the list of cost centers if the user returned to the Organization Details page after performing the change. This PR fixes the issues by applying a "network-only" fetch policy to the "get cost centers" GraphQL query. It also adds it to the "get users" query just to be safe. 
Linked here: https://b2bsuite--sandboxusdev.myvtex.com
Delete a cost center (either in the admin or in the My Account > My Organization page) and then return to the list of cost centers. The cost center should no longer appear. 
Similarly, add or remove an address from a cost center, then return to the list of cost centers. The "addresses" column should show the new …
=> [B2BORG-72] Disable GraphQL frontend cache

CHANGELOG.md, react/components/OrganizationUsersTable.tsx, react/components/UserWidget.tsx, react/utils/constants.ts
The current use of sessionStorage for user impersonation needs to be improved
This is related to what Sofia was reporting this morning while testing telemarketing app impersonation
Added a sessionStorage remove item (b2b-checkout-settings) when a new impersonation or stop impersonation is called
1) You have to start an impersonation by accessing your profile linked to the organization and then start an impersonation process.
2) So you should add some product to the cart and then go to the checkout page
3) Opening the network and you are able to see the session storage as image below:
4) Going back to the home page /, if you click on stop impersonation or start a new impersonation, the sessions storage should be empty after both processes.
=> [PERMISSION-26] Improve handling for impersonation expiration

CHANGELOG.md, react/admin/CostCenterDetails.tsx, react/components/CostCenterDetails.tsx, react/components/NewAddressModal.tsx
Added a new feature on creating the new address on the cost center which allows the user to set as the default address the new one.
Add an optional makeDefault boolean variable to createCostCenterAddress which if true would add the address to the beginning of the array instead of the end
Workspace:
[https://b2borg--sandboxusdev.myvtex.com/](https://b2borg--sandboxusdev.myvtex.com/)
=> [B2BORG-90] add an optional makeDefault boolean variable to createCostCenterAddress

CHANGELOG.md, react/admin/OrganizationDetails.tsx, react/graphql/getSalesChannels.graphql
Trade policies (AKA sales channels) also act as pricing tables, but only
the main one is included in the priceTables query. Introduce an
additional query to fetch the data for those and include it in the
display. This required a bit of tweaking of the UI logic since trade
policies have a display name plus a numerical id vs just a string name
for the regular price channels.
I don't know if you can access it, but I've got it running in a workspace on the Whitebird store
[Workspace](https://witi167--whitebird.myvtex.com)
=> Show trade polices as options in price table listing

.github/workflows/cypress.yml, cy-runner.yml
As the execSync timeout option failed yesterday, this forces GitHub Action to kill after 30 minutes.
=> ADD Timeout for Cypress on GitHub Action

CHANGELOG.md, admin/navigation.json, messages/context.json, messages/en.json, react/admin/OrganizationDetails.tsx, react/admin/OrganizationDetails/OrganizationDetailsCollections.tsx, react/admin/OrganizationDetails/OrganizationDetailsConstCenters.tsx, react/admin/OrganizationDetails/OrganizationDetailsDefault.tsx, react/admin/OrganizationDetails/OrganizationDetailsPayTerms.tsx, react/admin/OrganizationDetails/OrganizationDetailsPriceTables.tsx, react/admin/OrganizationDetails/OrganizationDetailsUsers.tsx, react/admin/OrganizationDetails/useHashRouter.ts, react/admin/OrganizationRequestDetails.tsx, react/admin/OrganizationRequestsTable.tsx, react/admin/OrganizationsList.tsx, react/admin/OrganizationsTable.tsx, react/admin/utils/messages.ts, react/package.json, react/yarn.lock
[Reference the B2B UX epic ticket](https://vtex-dev.atlassian.net/browse/USAAPPTEAM-531) for the full summary, reports, shared google drive, and detailed mockups related to these UX improvements.
Move the organization management into a single screen with 2 separate tabs for approved organizations and organization requests
Keep the same URLs when the tabs are loaded
This ticket is ONLY for adding the tabs UI. Any other changes displayed in the mockup will need separate Jira tickets
Create separate tabs for displaying the various data required for setting up and managing an Organization
The current tabs for the Organization detail page will be:
- Details
- Cost Centers
- Collections
- Payment Terms
- Price Tables
Using tabs will reduce the need for scrolling by only loading the UI for the …
=> [B2BORG-91]  Add tabs to the UI for Organizations and Organization details screens

CHANGELOG.md, react/admin/OrganizationDetails/OrganizationDetailsCollections.tsx, react/admin/OrganizationDetails/OrganizationDetailsPayTerms.tsx, react/admin/OrganizationDetails/OrganizationDetailsPriceTables.tsx
- The message on the bulk actions in the b2b org settings might be misleading. This needs to be adjusted. 
- Update the text from bulk actions text
- Change message from `messages.removeFromOrg` to `messages.addToOrg`
- This change was applied to the following tabs: `Price Tables, Payment Terms, Collections`
- This can be test on [this](https://beto--sandboxusdev.myvtex.com/admin/b2b-organizations/organizations/1edc154f-b557-11ec-835d-126883cbf753/#/price-tables) environment
=> [B2BORG-128] update message in bulk action buttons

CHANGELOG.md, react/components/RequestOrganizationForm.tsx
- Currently when the user creates an organization, they are stuck on the same page.
- When the user is authenticated, the page needs to auto refresh so they can see the products
You can test it [here](https://albertob2b--b2bstoreqa.myvtex.com/)
Scenarios: 
- Create an Organization without signing in, go straight to `/organization-request` 
**Expected Result**
_Should not redirect you because you are not authenticated_ 
- Create an Organization and have the `Auto Approve` enabled
**Expected Result**
_Should not redirect you because you are not authenticated_ 
- Sign in and create an Organization
**Expected Result**
_Should redirect you because you are authenticated_
=> Refresh page if authenticated and autocreate enabled

CHANGELOG.md, react/admin/CostCenterDetails.tsx, react/components/CostCenterDetails.tsx
- A client is currently trying to hide a couple of fields in the Cost Center details page
- Css Handles were added in order to achieve request
- You can test it [here](https://alberto--whitebird.myvtex.com/)
=> Add cost center details CSS Handles to hide specific fields

CHANGELOG.md, docs/README.md, react/components/UserWidget.tsx, store/contentSchemas.json
Prevent layout shifts between loading and loaded states of user widget data.
[Workspace](https://dev--bravtexfashionb2b.myvtex.com/)
Example usage on theme app:
```json
"b2b-user-widget": {
"props": {
"showLoadingIndicator": true
}
}
```
Preview gif: https://tiago-dev.com/files/screen-record.gif
In preview gif, the `b2b-user-widget` is inside a `overlay-layout` and widget loading indicator appears first on click at respective `overlay-trigger` (link with text "Minha Organização").
=> feat: possibility of loading indicator on widget

CHANGELOG.md, react/components/OrganizationDetails.tsx, react/components/utils/messages.ts
The "Back" button was not showing up in My Organization page under My Account, preventing the shopper from accessing other options from My Account when navigating on mobile.
* Login into the store
* Go to My Account menu
* Go to My Organization
* Click on back button at the top of the page and check it goes back to My Account page (or profile page if not on mobile)
[Workspace](https://enzo--osterclqab2b.myvtex.com/)
N/A
N/A
=> Fix missing back button in shopper my organizations page

CHANGELOG.md, react/admin/OrganizationDetails/OrganizationDetailsCollections.tsx, react/admin/OrganizationDetails/OrganizationDetailsPayTerms.tsx, react/admin/OrganizationDetails/OrganizationDetailsPriceTables.tsx, react/admin/OrganizationDetails/OrganizationDetailsSellers.tsx, react/admin/OrganizationSettings.tsx, react/admin/utils/organizationBulkAction.ts
The "Remove from org" button was not shown properly in a few places in the b2b organization admin page. That is because `.name` is not necessarily filled depending on how the build is done, which was the case here.
To avoid that, now we provide the proper label for the button instead of trying to infer from provided callback function name. 
Go into any organization details and try to add/remove something in the collections and/or payments options and/or sellers tab.
[Workspace](b2bsuite.myvtex.com/admin/b2b-organizations/organizations/)
=> fix: provide actual label instead of inferring from function .name

CHANGELOG.md, react/admin/OrganizationsTable.tsx
Updating the layout and tabs of the organizations pages to use Admin UI instead of Styleguide. This will make it more consistent with the rest of the admin as well as with features that we're planning to add to these pages. 
The following workspace has the new style. I've verified that all 4 pages are working as expected, and that switching between them works, as well as refreshing the page after switching tabs.
[Workspace](https://mairatabs--b2bstoreqa.myvtex.com/admin/b2b-organizations/organizations/#/organizations)
**Before**
**After**
=> Update layout and tabs to the new admin style

CHANGELOG.md, react/admin/OrganizationsList.tsx, react/admin/OrganizationsTable.tsx, react/components/CreateOrganizationButton/CreateOrganizationButton.tsx, react/components/CreateOrganizationButton/index.tsx, react/components/CreateOrganizationModal/CreateOrganizationModal.tsx, react/components/CreateOrganizationModal/index.tsx, react/components/CustomFieldInputList/CustomFieldInputList.tsx, react/components/CustomFieldInputList/index.tsx, react/components/RequestOrganizationForm.tsx, react/organizations/hooks.ts
This is moving the button for creation organizations to the topbar, which is the new Admin standard for these page actions.
The change seems simple, but it required a lot more code than the previous and bigger visual change of my previous PR (related to updating layout + tabs). I didn't actually change much of the code though, I just refactored a big part of it so I could split the creation button + modal from the organizations list, since they were within the same file. I'll comment inline to further explain the changes.
Create a few organizations in the workspace below and check that they're being correctly created as before.
Also, if the new organization's name is such that it would show up at the top of the initial organizations table on the page, it correctly shows up there just like …
=> Move creation button to the topbar

CHANGELOG.md, react/components/UserWidget.tsx, react/utils/metrics/changeTeam.ts, react/utils/metrics/impersonate.ts, react/utils/metrics/metrics.ts
Send to analytics events related to Change Team.
Logged with a user who has access to more than one organization/cost center, select the new organization and cost center on the top menu and click in Configure Current Organization button.
Events should appear in analytics redshift in a hour or so, into "vtex"."schemaless"."b2b_suite_buyerorg_data_raw" schema
[Workspace](https://takeda--b2bstore005.myvtex.com/)
Types:
```
type ChangeTeamFieldsMetric = {
date: string
user_id: string
user_role: string
user_email: string
org_id: string
cost_center_id: string
}
type ChangeTeamMetric = Metric & { fields: ChangeTeamFieldsMetric }
export type ChangeTeamMetric = {
kind: 'change-team-ui-event'
description: 'User change team/organization - UI'
}
export type Metric = {
name: 'b2b-suite-buyerorg-data' …
```
=> Change Team Metrics

CHANGELOG.md, react/components/EditUserModal.tsx, react/components/NewUserModal.tsx, react/components/OrganizationUsersTable.tsx
In our production case, we need to have the role/permission to be able to edit, delete, and add new users in any category (sales or Customers). 
We achieved the desired behavior by adding a handler for `manage-organization` permission. 
If the user has the role with `manage-organization` permission he should be able to:
- add, edit, or delete a user from any category;
- can set any role (not only by his category);
[Workspace](https://ilyapoc--helmethouseprod.myvtex.com)
=> add condition for "manage-organization" permission

CHANGELOG.md, react/components/OrganizationUsersTable.tsx
The users with the `sales` roles can't impersonate users, even if they have permission.
- Open the path /account#/organization, log with sales role account
- Go to Users
- Click in the 3 points to impersonate the user.
[Workspace](https://www.rivieraworks.ro/account?workspace=ki910328#/organization)
=> fix: remove the role slug check and use permission to impersonate user

react/B2BAdminLayout.tsx, react/components/BulkImportList/BulkImportList.tsx, react/components/CreateOrganizationButton/CreateOrganizationButton.tsx, react/package.json, react/yarn.lock
Once the bulk import components were refactored this PR aims add BulkImportProvider in the Layout of b2b-organizations app providing the translate function to the nested components that uses the "useTranslation" hook
[Arthurspace](https://arthurspace--b2bstoreqa.myvtex.com/admin/b2b-organizations/organizations#/organizations)
=> feat: Add BulkImportProvider in layout

react/components/BulkImportList/BulkImportList.tsx, react/components/ImportAlertList/ImportAlertList.tsx, react/hooks/useClosedAlerts.ts, react/hooks/useLocalStorage.ts
This pull request introduces a new feature that enables the removal of ImportAlerts upon clicking the dismiss button. The information about which ImportAlerts should be hidded is now registered in the LocalStorage.
[Workspace](https://removealert--b2bstoreqa.myvtex.com/admin/b2b-organizations/organizations#/organizations)
https://github.com/vtex-apps/b2b-organizations/assets/51174217/7b24e1ff-0bee-454f-ba38-ac6a13e66f56
=> Feat: Add removed alerts in localstorage

CHANGELOG.md, react/components/BulkImportList/BulkImportList.tsx, react/components/CreateOrganizationButton/CreateOrganizationButton.tsx, react/hooks/useBulkImportsQuery.ts
Currently, when an unauthorized user attempts to access the bulk import feature, an error is displayed. This PR addresses this issue by verifying the user's authorization to use the bulk import functionality. If authorized, the components from the feature are rendered. Additionally, a request is made to check for authorization, and upon successful validation, the "Import in bulk" option is displayed along with the Last Bulk Import Item.
[Workspace](https://testpermissions--b2bstoreqa.myvtex.com/admin/b2b-organizations/organizations#/organizations)
[B2BTEAM-1540](https://vtex-dev.atlassian.net/browse/B2BTEAM-1540)
[B2BTEAM-1540]: https://vtex-dev.atlassian.net/browse/B2BTEAM-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix the fetch data retry on Bulk Imports

CHANGELOG.md, react/admin/OrganizationDetails/OrganizationDetailsCollections.tsx, react/admin/OrganizationDetails/OrganizationDetailsCostCenters.tsx, react/admin/OrganizationDetails/OrganizationDetailsPayTerms.tsx, react/admin/OrganizationDetails/OrganizationDetailsPriceTables.tsx, react/admin/OrganizationDetails/OrganizationDetailsSellers.tsx
Solves the problem where the collections tab of the admin organization details page does not allow pagination through the available collections (although the `##-## of ##` text would change, the actual list of collections would never change). Also solves the problem where the initial collections query did not set any pageSize variable, resulting in only 20 records being returned. Also removes the option to show 100 collections per page, as the API allows a maximum of 50 to be returned at once.
This PR also adds loading indicators to the admin organization details page, in the following tabs: cost centers, collections, payment terms, price tables, and sellers.
New version linked here: https://arthur--cosmorentals.myvtex.com/admin/b2b-organizations/organizations/7f7780af-dbfe-11ee-8452-0ecf4 …
=> Fix: collections pagination and other admin UX improvements

CHANGELOG.md, react/admin/OrganizationDetails/OrganizationDetailsSellers.tsx, react/graphql/getSellersPaginated.graphql
On the B2B Organization Details Screen, the view of salespeople is limited to the first 100 records. This limit prevents users from selecting salespeople who are not among the first 100.
Go to Applications and in the ORGANIZATIONS AND B2B COST CENTERS subcategory and click on Organizations. Then, click on an Organization and go to the Sellers tab:
[Workspace](https://icaroov--b2bstore005.myvtex.com/admin/b2b-organizations/organizations/ac77fcd0-49c4-11ef-8452-0e41f4141887/#/sellers)
=> fix: Implement pagination for sellers in Organization Details page

CHANGELOG.md, react/admin/OrganizationDetails/OrganizationDetailsCollections.tsx, react/admin/OrganizationDetails/OrganizationDetailsCostCenters.tsx, react/admin/OrganizationDetails/OrganizationDetailsSellers.tsx, react/admin/OrganizationRequestsTable.tsx, react/components/OrganizationsWithoutSalesManager.tsx
Update pagination selected option in Organization Details pages
Go to Admin -> Apps -> Organizations -> Sellers
[Workspace](https://icaroov--b2bstore005.myvtex.com/admin/b2b-organizations/organizations/ac77fcd0-49c4-11ef-8452-0e41f4141887/#/sellers)
https://github.com/user-attachments/assets/63536aa9-0892-4646-9eaf-f56f179a673b
=> fix: adjust pagination with `selectedOption` prop on Organizations Details pages

CHANGELOG.md, react/admin/OrganizationsList.tsx
Fix hardcoded url
[Workspace](Link goes here!)
=> Update hardcoded URL

react/components/UserWidget.tsx
When there's a missing field either on organization name or cost center it raises an error
[marcofbb workspace](https://marcofbb--cromosol.myvtex.com/)
=> fix: add org name and cost center normalization when getting active orgs for userWidget
