CHANGELOG.md, messages/context.json, messages/en.json, react/admin/OrganizationsTable.tsx, react/components/UserWidget.tsx, react/graphql/getOrganizationStorefront.graphql
Show organization status in user widget
Linked in https://quotes--sandboxusdev.myvtex.com
=> [B2BORG-19] Show org status in user widget

manifest.json
Previous PR was merged without selecting CI/CD bot options, this is a new PR to retry the automatic publish
=> New PR to retry CI/CD bot publish

.github/workflows/lint.yml, .github/workflows/pull-request.yml, .github/workflows/sonarcloud.yml, sonar-project.properties
Just adding quality engineering actions. Before merge, please add SONAR_TOKEN secret.
=> ADD Quality Engineering

CHANGELOG.md, docs/README.md, react/admin/CostCenterDetails.tsx, react/admin/OrganizationDetails.tsx, react/admin/OrganizationsTable.tsx, react/components/CostCenterDetails.tsx, react/components/EditAddressModal.tsx, react/components/EditUserModal.tsx, react/components/NewAddressModal.tsx, react/components/NewCostCenterModal.tsx, react/components/NewUserModal.tsx, react/components/RequestOrganizationForm.tsx, react/graphql/removeUser.graphql, react/modules/formValidators.ts, react/utils/addresses.ts
Fixes a bunch of minor UI bugs mostly having to do with form validation. See changelog for full details.
Linked in https://quotes--sandboxusdev.myvtex.com
=> [B2BORG-45] Fix various UI and form validation bugs

CHANGELOG.md, docs/README.md, manifest.json
Remove billing options so that this app can be a dependency of the upcoming `vtex.b2b-suite`
=> [B2BORG-65] Remove billing options

cy-runner.yml
Removed vtex.store-theme from productusqa and Installed bitcot-qa-theme.
So, in setup we need to uninstall bitcot-qa-theme
=> in productusqa account, replaced store-theme with bitcot-qa-theme

CHANGELOG.md, messages/context.json, messages/en.json, react/components/RequestOrganizationForm.tsx, react/components/utils/messages.ts
Add duplicate check for an email that is already associated with a pending or approved request
[https://aurora--sandboxusdev.myvtex.com/account#/organization](url)
1. sign in to your account
2. change your email to `aurora.shen@vtex.com.br` or an email that has an existing pending or approved request 
3. you should see the toast message telling you have an existing pending or approved the request and are not able to submit
=> [B2BORG-82] Check duplicate requests

.github/workflows/cypress.yml
Just adding Cypress tests to run on a schedule basis.
=> ADD Run Cypress on a schedule basis

CHANGELOG.md, react/components/RequestOrganizationForm.tsx, react/graphql/createOrganizationRequest.graphql
Fixed duplicate check to get the status from createOrganizationRequest instead of checking it in RequestOrganizationForm.tsx
In workspace [https://b2borg--sandboxusdev.myvtex.com](url), 
Login in and send a new organization request
=> [B2BORG-96] Fix duplicate check

CHANGELOG.md, react/components/OrganizationUsersTable.tsx, react/components/RequestOrganizationForm.tsx, react/graphql/addUser.graphql, react/graphql/createOrganizationRequest.graphql, react/graphql/updateUser.graphql
It was created a mutation for addUser and updateUser, so this PR will change the frontend to those.
Environment:[ https://b2borg2--sandboxusdev.myvtex.com/]( https://b2borg2--sandboxusdev.myvtex.com/)
1) Login into store as Org Admin
2) Go to my account
3) My Organization
4) You will be able to add some users and see the mutation on the Networking tab
=> [B2BORG-97] Changes to B2B frontend component for adding vs editing user accounts

.github/workflows/sonarcloud-external.yml
Fix error on SonarCloud for external developers.
=> FIX Takeout node folder from GitHub Action

.github/workflows/cypress.yml, cy-runner.yml, package.json
=> As per latest flow, Updated cy-runner.yml

CHANGELOG.md, messages/de.json
This is part of a series of PRs in several apps to make German available across the Admin. Tracked in task [LOC-9843](https://vtex-dev.atlassian.net/browse/LOC-9843).
A test store with DE in the language switcher is [available here](https://localizationqa--obidev.myvtex.com/admin/).
[LOC-9843]: https://vtex-dev.atlassian.net/browse/LOC-9843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  Fix German translation.

.github/workflows/qe-pull-request-target.yml, .github/workflows/qe-pull-request.yml, CHANGELOG.md
- Disable cypress tests in PR level
#changingTooling
=> [ENGINEERS-1247] - Disable cypress tests in PR level 

messages/ar.json, messages/bg.json, messages/ca.json, messages/context.json, messages/cs.json, messages/da.json, messages/de.json, messages/el.json, messages/en.json, messages/es.json, messages/fi.json, messages/fr.json, messages/id.json, messages/it.json, messages/ja.json, messages/ko.json, messages/nl.json, messages/no.json, messages/pl.json, messages/pt.json, messages/ro.json, messages/ru.json, messages/sk.json, messages/sl.json, messages/sv.json, messages/th.json, messages/uk.json, react/bulkImport/messages.ts, react/package.json, react/yarn.lock
This PR updates the bulk-import-ui with the file validations and add the translations to the component
[Arthurspace](https://arthurspace--b2bstoreqa.myvtex.com/admin/b2b-organizations/organizations#/organizations)
=> Feat update bulk-import-ui with file validations

messages/ar.json, messages/bg.json, messages/ca.json, messages/cs.json, messages/da.json, messages/de.json, messages/el.json, messages/en.json, messages/es.json, messages/fi.json, messages/fr.json, messages/id.json, messages/it.json, messages/ja.json, messages/ko.json, messages/nl.json, messages/no.json, messages/pl.json, messages/pt.json, messages/ro.json, messages/ru.json, messages/sk.json, messages/sl.json, messages/sv.json, messages/th.json, messages/uk.json
This PRs Change the  bulk import uploading label
=> feat: Change the bulk import uploading label

react/components/CreateOrganizationButton/CreateOrganizationButton.tsx, react/hooks/bulkImportsMockData.ts, react/hooks/useBulkImportsQuery.ts, react/services/getBulkImportList.ts, react/types/BulkImport.d.ts
This PR fixes the integration with buyer-orgs route API, the initial integration was did in [the last PR as a test for SWR lib](https://github.com/vtex-apps/b2b-organizations/pull/134), in this PR the integration is finalized and some mutations are added in code.
[Arthurspace](https://arthurspace--b2bstoreqa.myvtex.com/admin/b2b-organizations/organizations)
[B2BTEAM-1410](https://vtex-dev.atlassian.net/browse/B2BTEAM-1410)
[B2BTEAM-1410]: https://vtex-dev.atlassian.net/browse/B2BTEAM-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Fix base integration for buyer orgs list

CHANGELOG.md, react/package.json, react/yarn.lock
=> Update bulk import ui

docs/README.md
=> EDU-12886 updating documentation

CHANGELOG.md, react/admin/OrganizationRequestDetails.tsx
Adds optional changing on organization request
=> fix: adds optional changing on organization request

CHANGELOG.md, messages/en.json, messages/es.json
Fix English and Spanish string for payment terms. Tracked in task [LOC-15586](https://vtex-dev.atlassian.net/browse/LOC-15586).
[LOC-15586]: https://vtex-dev.atlassian.net/browse/LOC-15586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix English and Spanish string for payment terms

docs/README.md
=> EDU-10979 Information added in the price table

docs/README.md
=> EDU-11238 Fixed link

docs/README.md
=> EDU-9598 Updated information about organization request

CHANGELOG.md, messages/es.json, react/components/UserWidget.tsx
Fixed wrong ES translation. Tracked in task [LOC-19505](https://vtex-dev.atlassian.net/browse/LOC-19505).
[LOC-19505]: https://vtex-dev.atlassian.net/browse/LOC-19505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix ES translation

CHANGELOG.md, manifest.json
Added policies
[Workspace](Link goes here!)
=> Patch added policies, changelog
